apiVersion: eno.azure.io/v1
kind: Synthesizer
metadata:
  name: mirror-synth
spec:
  image: $REGISTRY/mirror-synth
  command:
  - python3
  - /app/main.py
  refs:
    - key: input1
      resource:
        group: "" # core
        version: "v1"
        kind: ConfigMap
    - key: input2
      optional: true
      resource:
        group: "" # core
        version: "v1"
        kind: ConfigMap
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: some-input
data:
  example-key: example-value
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: dynamic-input-1
  labels:
    foo: bar2
data:
  example-key: example-value

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: dynamic-input-2
  labels:
    foo: bar2
data:
  example-key: example-value2

---

apiVersion: eno.azure.io/v1
kind: Composition
metadata:
  name: mirror-comp
spec:
  synthesizer:
    name: mirror-synth
  bindings:
    - key: input1
      resource:
        name: some-input
        namespace: default
    - key: input2
      resourceSelector:
        matchLabels:
          foo: bar2
